# This workflow creates a release using goreleaser
# via the 'make release' command.

name: Create release

on:
  push:
    branches:
      - dzmitryhil/trace-release

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Make release
        run: |
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 🧹 Clean release folder
        run: |
          sudo rm -rf dist
